server:
  port: 8081

spring:
  application:
    name: finpulse-market-simulator
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3

simulator:
  delay-ms: 100 # Emits updates every 100ms
