apiVersion: apps/v1
kind: Deployment
metadata:
  name: finpulse-backend
  labels:
    app: finpulse-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: finpulse-backend
  template:
    metadata:
      labels:
        app: finpulse-backend
    spec:
      containers:
        - name: finpulse-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finpulse-frontend
  labels:
    app: finpulse-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: finpulse-frontend
  template:
    metadata:
      labels:
        app: finpulse-frontend
    spec:
      containers:
        - name: finpulse-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
