apiVersion: v1
kind: Service
metadata:
  name: finpulse-backend-svc
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: finpulse-backend
---
apiVersion: v1
kind: Service
metadata:
  name: finpulse-frontend-svc
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: finpulse-frontend
