apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finpulse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/finpulse.git'
    targetRevision: HEAD
    path: infra/helm/finpulse
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finpulse-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
